### ISSUE TITLE
diffsims-0.3.0

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#106]
`diffsims-0.3.0` will depend on `orix-0.4.0` and be a platform for future releases of both `pyxem` and `kikuchipy`.

In this release we will address a number of long standing issues with `diffsims` and improve the architecture significantly.

This will include:

- [x] Removing sampling of orientation space from `diffsims` to inherit from `orix` #104 
- [x] Add the `ReciprocalLatticePoints` class, as a platform for unifying simulators. #111
- [x] Implementing more physical shape factors #23 and #114 

This will include significant contributions from several people, particularly including @JoonatanL @hakonanes and @pc494. This issue is raised to plan the development and to try and ensure that everyone is pulling in the same direction.

Please comment any suggestions, modifications to this, etc.

**Comment by pc494** [comment]
My plan is to finish #104, then build an architecture for physical shape functions, then will head back to #98 and helping out on #102

**Comment by pc494** [comment]
I would quiet like to drop #80 and #11 from this release so that we can get something out the door. That would make this 0.3 compatible with pyxem 0.12 and then 0.4 could contain most of the much needed overhaul and come out a point where it's acceptable to bump pyxem up a version too (with hot fixes)

**Comment by dnjohnstone** [comment]
> I would quiet like to drop #80 and #11 from this release so that we can get something out the door. That would make this 0.3 compatible with pyxem 0.12 and then 0.4 could contain most of the much needed overhaul and come out a point where it's acceptable to bump pyxem up a version too (with hot fixes)

Ok, if you want it sooner, go for it.

**Comment by pc494** [comment]
So, I think this push forward version will have #102 merged in (closing #23 and #32) and I will then tackle #107, #108, #109 and set up a release. Then we can sit down and think about some big picture ripping and rebuilding.

**Comment by hakonanes** [comment]
#111 is almost done as is, although not used at all in the code. If I did the renaming and wrote up tests, could we get that into 0.3 as well? Because I would very much like to use it in kikuchipy.

**Comment by pc494** [comment]
That's fine by me, soft deadline was the end of the month so you've got plenty of time to work with

**Comment by hakonanes** [comment]
> That's fine by me, soft deadline was the end of the month so you've got plenty of time to work with

Great, thanks, will get that done this week.

**Comment by dnjohnstone** [comment]
Ok - so I think we're at the point where it's merge #111 and #114 then we're done? I've updated the checklist to reflect that.

**Comment by pc494** [comment]
> Ok - so I think we're at the point where it's merge #111 and #114 then we're done? I've updated the checklist to reflect that.

And (newly) #115 and then yes, we will be release ready.

**Comment by dnjohnstone** [comment]
Great - just #111 now I think :)

**Comment by pc494** [comment]
Once #119 is in I'll package this up for release, probably early next week.
