### ISSUE TITLE
diffsims 0.4.0

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#141]
It seems very likely that we are going to want some of the additions to 0.4.0 to integrate into the forthcoming pyxem release. So we should start thinking about packaging what we've got.

Outstanding code:
- [x] Add a crude noise generator
- [x] ReciprocalLatticePoint behaves as expected with only one point #125
- [x] ~ReciprocalLatticePoint.families attribute, which lists the {hkl} families for all (hkl) in the list of points #133~
- [x] Random sphere mesh generator (#142)
- [x] ~Close issue #144~ 
- [x] Rename the testing folders so the test_ prefix is omitted (**FINAL** thing so as to avoid merge conflicts)

Points of note:
I will make the release of diffsims just **before** we release pyxem. This means that we can then set pyxem to depend directly on `0.4.0` from it's latest release onwards.

EDIT: calibration workflow component dropped, noise generator added.

**Comment by hakonanes** [comment]
Sounds good, will look at the mentioned issues this week. I don't have anything else at the moment.

**Comment by pc494** [comment]
This is now targetted for Wednesday 16th.

**Comment by pc494** [comment]
I have dropped closing #88 as a bit too much for now.

**Comment by hakonanes** [comment]
I've addressed #125 in PR #145 and #133 in #146, but I'm not sure if I can get these done so that you can release diffsims tomorrow...

I don't have anything else after these.

**Comment by pc494** [comment]
Yeah, we're going to miss Wednesday 16th, but everything that needs doing is open and in public (well apart from a PR #145, but that's not going to be massive). I am going to package up on Monday 21st if all things go smoothly (possibly as a `rc` if required to keep pyxem 0.12.3 running)

**Comment by hakonanes** [comment]
> (well apart from a PR #145, but that's not going to be massive)

What do you mean by this? As in that one is done, but the other PRs aren't? Because I think the `ReciprocalLatticePoint` class now treats having one vector OK.

**Comment by pc494** [comment]
Sorry, I got the wrong PR number, I meant #144, which is about moving point--->vector

**Comment by pc494** [comment]
Our third release candidate should do the trick, with a full release at the end of the week.

**Comment by hakonanes** [comment]
I've moved remaining issues tagged with v0.4.0 to either v0.4.1 or v0.5.0
