### ISSUE TITLE
Small changes for patch versions

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#79]
These things are too small to be their own issues.

- [ ]  Have the correct sections of code ascribed to @robtovey on github (is now #97)
- [ ] Tidy up the syntax inside the streographic generator (is now #93)
- [x] Reorder the plt.figure() statement in the docstrings for the zap map
- [x] Remove gimbal lock rotations from the euler generator (#82)
- [x] Check the euler generator gives good lists (maybe #82)
- [x] Prepare the refactorisation of excitation error to a structure/call of `calculate_ed_data()`
- [x] Prepare the refacotrisation allowing more complicated excitation error functions (#23)

**Comment by dnjohnstone** [comment]
Have we made any progress on this? No pressure, just trying to figure out where everything is at.

**Comment by dnjohnstone** [comment]
Given accelerating progress with various packages - would you be ok with us transforming this into a v0.3.0 to do list?

I'd also like to:

1. Add a ring_pattern_simulator somewhere to factor it out of the CalibrationGenerator in pyxem.
2. Impose black code style

**Comment by dnjohnstone** [comment]
@pc494 are you still interested in making these changes for 0.3.0?

**Comment by pc494** [comment]
Yep, I will tick the bottom two off as they are covered by #23 and then open a PR in the next couple of days to do the other two, which shouldn't take too long.

EDIT: Not sure the Rob Tovey bit has been done?
